# Module 2 notebook - numpy and matplotlib

In DAMI module 2 numpy and matplotlib are the central topics. In this notebook I've collected and created exercises from various Parts in order to develop my numpy and matplotlib skills.

## Part 1: DataCamp

In this part I'll demonstrate basic numpy skills and my abilty to leverage on freely available course material. I've incorporated the exercises of the [numpy module](https://goo.gl/8HTXNc) from the Datacamp course _Intro to Python for Data Science_ into this notebook.

In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [3]:
# height is available as a regular list
height = [74, 74, 72, 72, 69, 71, 76]

# Import numpy
import numpy as np

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 72 69 71 76]
[ 1.8796  1.8796  1.8288  1.8288  1.7526  1.8034  1.9304]


In [4]:
# height and weight are available as a regular lists
height = [74, 74, 72, 72, 69, 71, 76]
weight = [180, 215, 210, 210, 188, 176, 209]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[ 23.11037639  27.60406069  28.48080465  28.48080465  27.76243923
  24.5467457   25.43999693]


In [12]:
# height and weight are available as a regular lists
height = [74, 74, 72, 72, 69, 71, 76]
weight = [180, 215, 210, 210, 188, 176, 209]

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 25

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 25
print(bmi[light])

[ True False False False False  True False]
[ 23.11037639  24.5467457 ]


In [17]:
# Import numpy
import numpy as np

np_array1 = np.array([True, 1, 2]) + np.array([3, 4, False])
np_array2 = np.array([4, 3, 0]) + np.array([0, 2, 2])

# Compare (True is converted to 1, False is converted to 0)
print(np_array1 == np_array2)

[ True  True  True]


In [19]:
# height and weight are available as a regular lists
height = [74, 74, 72, 72, 69, 71, 76]
weight = [180, 215, 210, 210, 188, 176, 209]

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 3
print(np_weight[3])

# Print out sub-array of np_height: index 2 up to and including index 4
print(np_height[2:5])

210
[72 72 69]


In [20]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [21]:
# baseball is available as a regular list of lists
baseball = [[74,180],[74,215],[72,210],[72,210],[69,188],[71,176],[76,209]]

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 5th row of np_baseball
print(np_baseball[4, :])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:, 1]

# Print out height of 2nd player
print(np_baseball[1, 0])

[ 69 188]
74


In [22]:
# baseball is available as a regular list of lists
baseball = [[74,180,27.34],[74,215,25.67],[72,210,31.49],[72,210,24.56],[69,188,37.19],[71,176,29.81],[76,209,30.17]]
updated = [[0.51,-0.54,1],[0.84,0.14,1],[0.27,0.84,1],[0.79,-0.47,1],[0.18,0.47,1],[0.73,0.11,1],[0.55,-0.73,1]]

# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[  74.51  179.46   28.34]
 [  74.84  215.14   26.67]
 [  72.27  210.84   32.49]
 [  72.79  209.53   25.56]
 [  69.18  188.47   38.19]
 [  71.73  176.11   30.81]
 [  76.55  208.27   31.17]]
[[  1.8796    81.64656   27.34    ]
 [  1.8796    97.52228   25.67    ]
 [  1.8288    95.25432   31.49    ]
 [  1.8288    95.25432   24.56    ]
 [  1.7526    85.275296  37.19    ]
 [  1.8034    79.832192  29.81    ]
 [  1.9304    94.800728  30.17    ]]


In [23]:
# Import numpy
import numpy as np

# np_baseball is available
np_baseball = np.array([[74,180,27.34],[74,215,25.67],[72,210,31.49],[72,210,24.56],[69,188,37.19],[71,176,29.81],[76,209,30.17]])

# Create np_height from np_baseball
np_height = np_baseball[:, 0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

72.5714285714
72.0


In [24]:
# np_baseball is available
np_baseball = np.array([[74,180,27.34],[74,215,25.67],[72,210,31.49],[72,210,24.56],[69,188,37.19],[71,176,29.81],[76,209,30.17]])

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 72.5714285714
Median: 72.0
Standard Deviation: 2.12852348939
Correlation: [[ 1.          0.41152133]
 [ 0.41152133  1.        ]]


In [25]:
# heights and positions are available as lists
positions = ['GK','M','A','D','A','D','M','D','A']
heights = [180,172,186,179,176,184,185,180,181]

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 180.0
Median height of other players: 180.5


## Part 3: ipythonblocks

Indexing skills are key in numpy as well as in pandas. In this part I'll demonstrate my numpy indexing skills using [ipythonBlocks](https://goo.gl/43TKxr). I've installed the package using condas and imported it into this notebook. I'll pay specific attention to complex slicing and fancy indexing and boolean indexing. Fancy and boolean indexing are extensions for numpy and pandas and not available in regular python sequences such as lists and strings.

In [30]:
from ipythonblocks import show_color, BlockGrid

In [27]:
show_color(12, 123, 234)

In [31]:
grid = BlockGrid(10, 10, fill=(123, 234, 123))
grid

In [34]:
for block in grid:
    if block.row % 2 == 0 and block.col % 2 == 0:
        block.red = 0
        block.green = 0
        block.blue = 0
grid

In [36]:
for r in range(grid.height):
    for c in range(grid.width):
        sq = grid[r, c]
        sq.red = 100
        
        if r % 2 == 0:
            sq.green = 15
        else:
            sq.green = 255
        
        if c % 2 == 0:
            sq.blue = 15
        else:
            sq.blue = 255
grid.show()

In [37]:
sub_grid = grid[:,5]
sub_grid.show()

In [60]:
import numpy as np
np_array = np.array([True, False, True, True, False])

grid = BlockGrid(len(np_array), 1, fill=(0, 0, 0))

for block in grid:
    if (np_array[block] == 1:
        block.red = 255
        block.green = 0
        block.blue = 0
grid.show()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

## Part 2: numpy exercies notebook

This part contains a selection of exercises from the [numpy 100 exercises notebook](http://bit.ly/2vN6N4F) on GitHub. I've selected some exercises that felt sufficiently challenging and that learned me something new. I've paid special attention to

- indexing (sliced, fancy, boolean/masked)
- vectorization
- broadcasting
- aggregation

These are all concepts that make numpy very efficient for vector based computing. scikit-learn algorithms heavily depend on these concepts.

## Part 3: Python Data Science Handbook - numpy

This part contains selected examples from the [Python Data Science Handbook](https://goo.gl/ay9Bqe). I've read through the chapter on numpy an matplotlib and here are some exercises I've extracted from them. I've adapted the code demos from the book slightly in order to better understand and learn specific features and functionality.
I end with the k-Nearest Neighbors example from the book, as this gives me some insight in the implementation of a simple machine learning algorithm.

## Parts 4: Python Data Science Handbook - matploblib

Finally I've created my own numpy dataset with randomized data. I'll use it to demonstrate my matplotlib visualization skills in the same fashion as has been done in the matplotlib chapter in the [Python Data Science Handbook](https://goo.gl/ay9Bqe).